import { Link } from "react-router-dom";
import { ArrowRight, Database, ShieldAlert } from "lucide-react";
import { AppShell } from "@/components/medmap/AppShell";
import { useMedMap } from "@/lib/medmap-store";

type ModuleKey = "doctor-acquisition" | "ambassadors" | "sales" | "customer-operations" | "technology" | "risk" | "reports" | "admin" | "organization";
const moduleContent: Record<ModuleKey, { eyebrow: string; title: string; description: string; owner: string; next: string; links: { label: string; to: string }[] }> = {
  "doctor-acquisition": { eyebrow: "Operations · Doctor Acquisition", title: "Doctor acquisition, with a source for every enrolment.", description: "This module is ready for doctor records, acquisition source, specialty, geography, subscription state and campaign history. It will consume live MedMap doctor data instead of inventing counts.", owner: "COO · Kuhlula Madumo", next: "Awaiting live doctor records and acquisition-source data.", links: [{ label: "Set acquisition targets", to: "/meetings" }, { label: "Open company KPIs", to: "/kpis" }] },
  ambassadors: { eyebrow: "Operations · Ambassador Programme", title: "Ambassador cohorts, referrals and monthly performance.", description: "Cohort and commission rules belong here, with monthly tier history preserved. No ambassador activity is shown until real ambassador records are connected.", owner: "COO · Kuhlula Madumo", next: "Awaiting live ambassador records and referral activity.", links: [{ label: "Open COO tickets", to: "/meetings" }, { label: "Open finance", to: "/finance" }] },
  sales: { eyebrow: "Operations · Sales", title: "Sales is separate from ambassador acquisition.", description: "This module will track the doctor upsell pipeline, patient conversion, owners, follow-ups and revenue by stage. Conversion assumptions will be configuration, not permanent facts.", owner: "COO · Kuhlula Madumo", next: "Awaiting live sales leads and conversion records.", links: [{ label: "Open COO tickets", to: "/meetings" }, { label: "Open company KPIs", to: "/kpis" }] },
  "customer-operations": { eyebrow: "Operations · Customer Operations", title: "Cases, SLAs and resolution ownership.", description: "Customer Operations is modelled as cases rather than generic tickets. Case records will include patient/doctor context, response timestamps, SLA, escalation and resolution.", owner: "COO · Kuhlula Madumo", next: "Awaiting live customer case records.", links: [{ label: "Open operations work", to: "/operations" }, { label: "Record a meeting", to: "/meetings" }] },
  technology: { eyebrow: "Technology · Product, Engineering & Security", title: "Technology delivery with blockers visible.", description: "The current CTO delivery queue is connected. Product roadmap, engineering backlog, security findings, infrastructure and AWS migration remain separate records as they are added.", owner: "CTO · Selaelo Princess Langa", next: "Current blockers are shown on Meetings & deadlines and the command centre.", links: [{ label: "Open technology queue", to: "/meetings" }, { label: "Open command centre", to: "/" }] },
  risk: { eyebrow: "Risk & Governance", title: "Risk, compliance and governance actions.", description: "This module will hold the risk register, owners, mitigation, POPIA/PAIA controls, policies, security incidents and overdue governance actions.", owner: "CEO · Ofentse Mashau", next: "Awaiting governed risk and compliance records.", links: [{ label: "Open company KPIs", to: "/kpis" }, { label: "Open technology", to: "/technology" }] },
  reports: { eyebrow: "Reporting", title: "Reports built from connected records.", description: "Daily, weekly and monthly views will be calculated from KPIs, finance, acquisition, cases, tickets and technology records. No report is populated with synthetic production activity.", owner: "CEO · Ofentse Mashau", next: "Awaiting the live MedMap API/database connection.", links: [{ label: "Open company KPIs", to: "/kpis" }, { label: "Open finance", to: "/finance" }] },
  admin: { eyebrow: "Settings · Administration", title: "Controlled business configuration.", description: "Targets, thresholds, commission rules, pricing, probation, dormancy and booking rules should be changed here by authorised users rather than in source code.", owner: "CEO · Ofentse Mashau", next: "Prototype permissions remain local; backend authentication/RBAC is still required for production enforcement.", links: [{ label: "Open company KPIs", to: "/kpis" }, { label: "Open People & goals", to: "/people" }] },
  organization: { eyebrow: "Executive · Organisation", title: "The MedMap reporting structure.", description: "CEO oversees the company. COO owns Operations, Doctor Acquisition, Ambassador Programme, Sales and Customer Operations. CTO owns Product, Engineering and Technology & Security.", owner: "CEO · Ofentse Mashau", next: "Employee records now carry department, team, role, manager and reporting line.", links: [{ label: "Open People & goals", to: "/people" }, { label: "Open company KPIs", to: "/kpis" }] },
};

export default function ModulePage({ module }: { module: ModuleKey }) {
  const content = moduleContent[module];
  const { organizationUnits } = useMedMap();
  return <AppShell><div className="mx-auto max-w-[1200px] px-5 pb-12 pt-8 sm:px-8 xl:px-10"><div className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.17em] text-[#4a87c9]"><Database size={13} /> {content.eyebrow}</div><h1 className="max-w-[820px] font-display text-[32px] font-bold tracking-[-0.06em] text-[#152239] sm:text-[39px]">{content.title}</h1><p className="mt-3 max-w-[760px] text-[13px] leading-6 text-slate-500">{content.description}</p><div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1fr)_330px]"><section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_5px_20px_rgba(21,36,58,0.035)] sm:p-6"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-[#fff2d9] text-[#b3781f]"><ShieldAlert size={16} /></span><h2 className="font-display text-[16px] font-bold text-[#152239]">Current data state</h2></div><p className="mt-3 text-[12px] leading-6 text-slate-500">{content.next}</p><div className="mt-5 rounded-xl border border-dashed border-slate-200 bg-[#f7f9fb] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Accountable owner</p><p className="mt-2 text-[13px] font-bold text-slate-700">{content.owner}</p></div>{module === "organization" && <div className="mt-5 grid gap-2 sm:grid-cols-2">{organizationUnits.map((unit) => <div key={unit.id} className="rounded-xl border border-slate-100 p-3"><p className="text-[11px] font-bold text-slate-700">{unit.name}</p><p className="mt-1 text-[10px] text-slate-400">{unit.kind} · {unit.leader}</p></div>)}</div>}</section><aside className="rounded-2xl bg-[#182842] p-5 text-white shadow-[0_8px_24px_rgba(21,36,58,0.09)] sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#84e0c3]">Continue in the operating system</p><div className="mt-4 space-y-2">{content.links.map((link) => <Link key={link.to} to={link.to} className="flex items-center justify-between rounded-xl bg-white/10 px-3 py-3 text-[11px] font-bold text-white hover:bg-white/15">{link.label}<ArrowRight size={14} /></Link>)}</div></aside></div></div></AppShell>;
}
