import type { Transaction } from "./medmap-store";

export const workbookTransactions: Transaction[] = [
  {
    "id": "WB-001",
    "date": "2025-06-07",
    "description": "CIPC Hennospark",
    "kind": "expense",
    "category": "Pre-registration / company formation cost",
    "amount": 175,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-002",
    "date": "2025-07-21",
    "description": "CIPC Hennospark",
    "kind": "expense",
    "category": "Pre-registration / company formation cost",
    "amount": 175,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-003",
    "date": "2025-08-29",
    "description": "Replit — failed attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 3,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-004",
    "date": "2025-08-30",
    "description": "Lovable — failed attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 3,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-005",
    "date": "2025-08-30",
    "description": "Replit",
    "kind": "expense",
    "category": "Development software",
    "amount": 269.95,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-006",
    "date": "2025-08-30",
    "description": "Replit — failed attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 3,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-007",
    "date": "2025-08-31",
    "description": "Builder.io",
    "kind": "expense",
    "category": "Development software",
    "amount": 536.97,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-008",
    "date": "2025-08-31",
    "description": "Lovable",
    "kind": "expense",
    "category": "Development software",
    "amount": 447.98,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-009",
    "date": "2025-09-01",
    "description": "Replit — failed attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 3,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-010",
    "date": "2025-09-04",
    "description": "Replit — failed attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 3,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-011",
    "date": "2026-01-08",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-012",
    "date": "2026-01-09",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-013",
    "date": "2026-01-12",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-014",
    "date": "2026-01-17",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-015",
    "date": "2026-01-18",
    "description": "Medmap (pty) Ltd — direct funding",
    "kind": "funding",
    "category": "Direct founder funding",
    "amount": 407,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "owedTo": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Cash sent directly to MedMap. Do not also classify the same cash movement as a MedMap expense."
  },
  {
    "id": "WB-016",
    "date": "2026-01-21",
    "description": "Render — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-017",
    "date": "2026-01-22",
    "description": "Netlify",
    "kind": "expense",
    "category": "Hosting / deployment",
    "amount": 150.47,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-018",
    "date": "2026-02-04",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-019",
    "date": "2026-02-04",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-020",
    "date": "2026-02-04",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-021",
    "date": "2026-02-04",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-022",
    "date": "2026-02-06",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-023",
    "date": "2026-02-06",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-024",
    "date": "2026-02-08",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-025",
    "date": "2026-02-08",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-026",
    "date": "2026-02-08",
    "description": "Render — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-027",
    "date": "2026-02-09",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-028",
    "date": "2026-02-12",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-029",
    "date": "2026-02-17",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-030",
    "date": "2026-03-05",
    "description": "Render — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-031",
    "date": "2026-03-05",
    "description": "Render — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-032",
    "date": "2026-03-05",
    "description": "Render — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-033",
    "date": "2026-03-05",
    "description": "Render — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-034",
    "date": "2026-03-06",
    "description": "Render — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-035",
    "date": "2026-03-08",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-036",
    "date": "2026-03-08",
    "description": "Render — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-037",
    "date": "2026-03-12",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-038",
    "date": "2026-03-12",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-039",
    "date": "2026-03-14",
    "description": "Netlify",
    "kind": "expense",
    "category": "Hosting / deployment",
    "amount": 150.3,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-040",
    "date": "2026-03-18",
    "description": "Medmap (pty) Ltd — direct funding",
    "kind": "funding",
    "category": "Direct founder funding",
    "amount": 4502,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "owedTo": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Cash sent directly to MedMap. Do not also classify the same cash movement as a MedMap expense."
  },
  {
    "id": "WB-041",
    "date": "2026-04-12",
    "description": "Microsoft",
    "kind": "expense",
    "category": "Software / subscription",
    "amount": 361.31,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Confirmed by management. Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-042",
    "date": "2026-04-13",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-043",
    "date": "2026-04-14",
    "description": "Host Africa",
    "kind": "expense",
    "category": "Hosting / domain infrastructure",
    "amount": 50,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-044",
    "date": "2026-04-14",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-045",
    "date": "2026-04-17",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-046",
    "date": "2026-04-17",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-047",
    "date": "2026-04-22",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-048",
    "date": "2026-05-01",
    "description": "Host Africa",
    "kind": "expense",
    "category": "Hosting / domain infrastructure",
    "amount": 50,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-049",
    "date": "2026-05-02",
    "description": "Host Africa",
    "kind": "expense",
    "category": "Hosting / domain infrastructure",
    "amount": 50,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-050",
    "date": "2026-05-09",
    "description": "Netlify",
    "kind": "expense",
    "category": "Hosting / deployment",
    "amount": 150.08,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-051",
    "date": "2026-05-13",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-052",
    "date": "2026-05-13",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-053",
    "date": "2026-05-14",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-054",
    "date": "2026-05-17",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-055",
    "date": "2026-05-22",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-056",
    "date": "2026-05-29",
    "description": "Microsoft",
    "kind": "expense",
    "category": "Software / subscription",
    "amount": 36.66,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Confirmed by management. Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-057",
    "date": "2026-05-29",
    "description": "Microsoft",
    "kind": "expense",
    "category": "Software / subscription",
    "amount": 478.03,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Confirmed by management. Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-058",
    "date": "2026-05-29",
    "description": "Netlify",
    "kind": "expense",
    "category": "Hosting / deployment",
    "amount": 149.66,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-059",
    "date": "2026-06-13",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-060",
    "date": "2026-06-14",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-061",
    "date": "2026-06-17",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-062",
    "date": "2026-06-22",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-063",
    "date": "2026-07-13",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-064",
    "date": "2026-07-15",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-065",
    "date": "2026-07-15",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-066",
    "date": "2026-07-16",
    "description": "Netlify",
    "kind": "expense",
    "category": "Hosting / deployment",
    "amount": 150.62,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-067",
    "date": "2026-07-16",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-068",
    "date": "2026-07-19",
    "description": "Microsoft",
    "kind": "expense",
    "category": "Software / subscription",
    "amount": 478.97,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Confirmed by management. Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-069",
    "date": "2026-07-19",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-070",
    "date": "2026-07-24",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-071",
    "date": "2026-08-27",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-072",
    "date": "2026-08-28",
    "description": "Netlify — insufficient-funds attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  },
  {
    "id": "WB-073",
    "date": "2026-08-29",
    "description": "DaVinci AI",
    "kind": "expense",
    "category": "Creative software",
    "amount": 33.9,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Confirmed by management. Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-074",
    "date": "2026-08-29",
    "description": "Netlify",
    "kind": "expense",
    "category": "Hosting / deployment",
    "amount": 141.62,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Successful business charge; confirm invoice/account where marked pending."
  },
  {
    "id": "WB-075",
    "date": "2026-08-31",
    "description": "Netlify — declined attempt",
    "kind": "expense",
    "category": "Business payment attempt fee",
    "amount": 2,
    "status": "Paid",
    "owner": "Ofentse Mashau",
    "source": "MedMap_business_transaction_classification.xlsx · Founder Funding Ledger",
    "notes": "Bank fee actually charged on an unsuccessful business-related payment attempt."
  }
];
